### ISSUE TITLE
Query block not supported by parent resources

### ISSUE THREAD

**Issue by alexkarpitski** [mediapills/cloud-custodian#67]
In a YAML policy the `query` block is intended to provide required parameters to a resource unless they can be retrieved from any other sources. As of now, the `QueryResourceManager` class can override the `get_resource_query` method in order to get these parameters. On the downside, the information is lost in the new `ChildResourceManager` class.

The solution proposed in [one of the commits](https://github.com/mediapills/cloud-custodian/pull/65/commits/3109da5e47757885887c67fc9b05529eec678b29) of [PR 65](https://github.com/mediapills/cloud-custodian/pull/65) works so that a parent resource is given the same parameters as the ones defined for its child. In addition to that, a new `get_parent_resource_query` method returning the result of get_resource_query by default has been introduced to control the parameters required for the parent and for the child separately.

Here are some examples of such resources:
- IoT Registry ([list](https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries/list) requires location which is not a resource);
- IoT Device (a child of IoT Registry);
- Firestore Document ([list](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/list) requires database which does not provide list nor get methods);
- Firestore Operation (the same as Firestore Document).

**Comment by alexkarpitski** [comment]
UPD: a new [version](https://github.com/cloud-custodian/cloud-custodian/pull/4171/commits/cfaf764ee37fed7e494d0a5e9181e8c978a96435) is proposed in https://github.com/cloud-custodian/cloud-custodian/pull/4171.

**Comment by jondavidi** [comment]
@alexkarpitski once the new change in #4171 is finalizd, please update all other PRs with the new technique.

**Comment by alexkarpitski** [comment]
https://github.com/cloud-custodian/cloud-custodian/pull/4171 is merged.
