### ISSUE TITLE
Actions implementation

### ISSUE THREAD

**Issue by evhenyshaliov** [mediapills/cloud-custodian#80]
There is available PR https://github.com/mediapills/cloud-custodian/pull/97 with delete action for spanner instance resource.

I suggest to implement actions by the following way:
- add action implementation in the service file (spanner.py),
- add a test for the action, that checks 
  - the action made changes with resources that had to be changed,
  - the action didn't make changes with resources that had not to be changed,
- create a use case for the action.

**Comment by aleonidex** [comment]
let's start from
 > create a use case for the action.
and implement only after this is done/clear.
